src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\OneToMany(targetEntity=ModelManga::class, mappedBy="Category")
     */
    private $modelMangas;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $images;

    public function __construct()
    {
        $this->modelMangas = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    /**
     * @return Collection|ModelManga[]
     */
    public function getModelMangas(): Collection
    {
        return $this->modelMangas;
    }

    public function addModelManga(ModelManga $modelManga): self
    {
        if (!$this->modelMangas->contains($modelManga)) {
            $this->modelMangas[] = $modelManga;
            $modelManga->setCategory($this);
        }

        return $this;
    }

    public function removeModelManga(ModelManga $modelManga): self
    {
        if ($this->modelMangas->removeElement($modelManga)) {
            // set the owning side to null (unless already changed)
            if ($modelManga->getCategory() === $this) {
                $modelManga->setCategory(null);
            }
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImages()
    {
        return $this->images;
    }

    public function setImages($images)
    {
        $this->images = $images;

        return $this;
    }

}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name')
            ->add('Description')
            ->add('images',
                    FileType::class,
                    [
                        // 'label' => 'Image',
                        'data_class' => null,
                        'required' => is_null($builder -> getData() -> getImages()),
                    ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\Serializer\SerializerInterface;
use App\Entity\Category;
use App\Form\CategoryType;
use App\Form\GenreType;
use Doctrine\DBAL\ForwardCompatibility\Result;
use Exception;

use function PHPUnit\Framework\throwException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\VarDumper\Cloner\Data;

/**
 * @IsGranted("ROLE_USER")
 */
class CategoryController extends AbstractController
{
     /**
     * @Route ("/category", name="category_index")
     */
    public function indexCategory() {
        $categorys = $this->getDoctrine()
                       ->getRepository(Category::class)
                       ->findAll();
        return $this->render(
            "category/index.html.twig",
            [
               "category" => $categorys
            ]
        );
    }

    /**
     * @Route ("/category/detail/{id}", name="category_detail")
     */
    public function detailCategory($id){
         $category = $this->getDoctrine()
                         ->getRepository(Category::class)
                         ->find($id);
         return $this ->render(
            "category/detail.html.twig",
            [
               "category" => $category
            ]
         );
     }

     
     /**
      *  @IsGranted("ROLE_ADMIN")
     * @Route ("/category/update/{id}", name="category_update")
     */
    public function updateCategory(Request $request, $id) {
        $category = $this -> getDoctrine() -> getRepository(Category::class) -> find($id);
        $form = $this -> createForm(CategoryType::class, $category);
        $form -> handleRequest($request);

        if($form -> isSubmitted() && $form -> isValid())
        {
            $uploadFile = $form['images'] -> getData();
            if($uploadFile != null)
            {
                $image = $category -> getImages();

                //create a unique image name
                $fileName = md5(uniqid());
    
                //get image extension
                $fileExtension = $image -> guessExtension();
                $imageName = $fileName . '.' . $fileExtension;
    
                try{
                    $image -> move(
                        $this -> getParameter('category_image'), $imageName
                    );
                }
                catch(FileException $e)
                {
                    throwException($e);
                }

                $category -> setImages($imageName);
            }

            $manager = $this -> getDoctrine() -> getManager();
            $manager -> persist($category);
            $manager -> flush();

            $this -> addFlash("Info","update successfully!");
            return $this -> redirectToRoute("category_index");
        }

        $this -> addFlash("Error","update false!");
        return $this -> render(
            "category/update.html.twig",
            [
                "form" => $form -> createView()
            ]
        );
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route ("/category/delete/{id}", name="category_delete")
     */
    public function deleteCategory($id) {
        try{
            $category = $this->getDoctrine()->getRepository(Category::class)->find($id);
            $chk = $category->getModelMangas();
            if(count($chk)>0){  
                $this->addFlash("Error","delete failed");
                return $this->redirectToRoute("category_index");
            }
            $manager = $this->getDoctrine()->getManager();
            $manager->remove($category);
            $manager->flush();
            $this->addFlash("Info", "Delete succeed !");
            return $this->redirectToRoute("category_index");
        }catch(Exception $e){
            throwException($e);
        }
    }


    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route ("/category/create", name="category_create")
     */
    public function createModelManga(Request $request)
    {
        $category = new Category();
        $form = $this -> createForm(CategoryType::class, $category);
        $form -> handleRequest($request);

        if($form -> isSubmitted() && $form -> isValid())
        {
            //get image 
            $image = $category -> getImages();

            //create a unique image name
            $fileName = md5(uniqid());

            //get image extension
            $fileExtension = $image -> guessExtension();
            $imageName = $fileName . '.' . $fileExtension;

            try{
                $image -> move(
                    $this -> getParameter('category_image'), $imageName
                );
            }
            catch(FileException $e)
            {
                throwException($e);
            }

            $category -> setImages($imageName);

            $manager = $this -> getDoctrine() -> getManager();
            $manager -> persist($category);
            $manager -> flush();

            $this -> addFlash("Info","Create successfully!");
            return $this -> redirectToRoute("category_index");
        }

        
        return $this -> render(
            "category/create.html.twig",
            [
                "form" => $form -> createView()
            ]
        );
    }
}

templates/category/create.html.twig
{% extends "base.html.twig" %}

{% block body %}
<div class="container">
    <h2 class="mt-5 mb-5 text-center"> Create Category </h2>
    <div class="col-md-6 offset-md-3"></div>
    {{ form_start (form) }}
        <div class="form-group">
            <h6 class="text-primary"> Category Name </h6>
            {{ form_widget (form.Name, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div>
        <h6 class="text-primary"> Model Image </h6>
        {{ form_widget (form.images, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Category Description </h6>
            {{ form_widget (form.Description, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group text-center mt-5">
            <button class="btn btn-info mt-2">CREATE</button>
        </div>
    {{ form_end (form) }}
</div>
{% endblock %}

templates/category/detail.html.twig
{% extends "base.html.twig" %}

{% block Name %}Category Detial{% endblock %}

{% block body %}
<style>
    body{
        width:80%;
        margin: 20px auto;
    }
    
</style>

<div class="container-fluid">
<a class="btn btn-outline-success" href="{{path('category_index')}}">Back Home</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Images </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td scope="col">{{category.name}}</td>
            <td scope="col">{{category.description}}</td>
            <td scope="col">
             {% if category.images == null %}
                         
                    {% else %}               
                        <img src = "{{asset('images/products/' ~ category.images)}}" width="300px">
  
                    {% endif %}
            </td>
            <td>
            <a class="btn btn-warning" href="{{path('category_update', {'id': category.id})}}">Update</a>
            <a class="btn btn-danger" href="{{path('category_delete', {'id': category.id})}}"
            onclick="return confirm('Warning!!! Are you sure to delete?')"
            >Delete</a>
            </td>
        </tr>    

    </tbody>
</table>
</div>

{% endblock %}

templates/category/index.html.twig
{% extends "base.html.twig" %}

{% block Name %}Category{% endblock %}

{% block body %}
<style>
    body{
        width:80%;
        margin: 20px auto;
    }
    
</style>

<div class="container-fluid">
<div class="container">
        {% for flash in app.flashes("Info") %}
            <p class="alert alert-success"> {{ flash }}
        {% endfor %}
        
    </div>
<a class="btn btn-outline-success" href="{{path('category_create')}}">Create Category</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Image</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
    {% for category in category %}
        <tr>
            <td scope="col">{{category.id}}</td>
            <td scope="col">{{category.name}}</td>
            <td scope="col"><img src = "{{asset('images/products/' ~ category.images)}}" width = "300px"></td>
            
            <td>
            <a class="btn btn-primary" href="{{path('category_detail', {'id': category.id})}}" >Detail</a>
            <a class="btn btn-warning" href="{{path('category_update', {'id': category.id})}}">Update</a>
            <a class="btn btn-danger" href="{{path('category_delete', {'id': category.id})}}"
            onclick="return confirm('Warning!!! Are you sure to delete?')"
            >Delete</a>
                                    
            </td>
        </tr>    
    {% endfor %}

    </tbody>
</table>
</div>

{% endblock %}

templates/category/update.html.twig
{% extends "base.html.twig" %}

{% block body %}
<div class="container">
    <h2 class="mt-5 mb-5 text-center"> Update Category </h2>
    <div class="col-md-6 offset-md-3"></div>
    {{ form_start (form) }}
        <div class="form-group">
            <h6 class="text-primary"> Category Name </h6>
            {{ form_widget (form.Name, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Category Image </h6>
            {{ form_widget (form.images, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Category Description </h6>
            {{ form_widget (form.Description, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group text-center mt-5">
            <button class="btn btn-info mt-2">UDPATE</button>
        </div>
    {{ form_end (form) }}
</div>
{% endblock %}