src/Entity/ModelManga.php
<?php

namespace App\Entity;

use App\Repository\ModelMangaRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ModelMangaRepository::class)
 */
class ModelManga
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="modelMangas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CharacterName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Series;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Price;

    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $Material;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $UsingModel;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $Publish_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getCharacterName(): ?string
    {
        return $this->CharacterName;
    }

    public function setCharacterName(string $CharacterName): self
    {
        $this->CharacterName = $CharacterName;

        return $this;
    }

    public function getSeries(): ?string
    {
        return $this->Series;
    }

    public function setSeries(string $Series): self
    {
        $this->Series = $Series;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getMaterial(): ?string
    {
        return $this->Material;
    }

    public function setMaterial(string $Material): self
    {
        $this->Material = $Material;

        return $this;
    }

    public function getUsingModel(): ?string
    {
        return $this->UsingModel;
    }

    public function setUsingModel(string $UsingModel): self
    {
        $this->UsingModel = $UsingModel;

        return $this;
    }

    public function getPublishDate(): ?\DateTimeInterface
    {
        return $this->Publish_date;
    }

    public function setPublishDate(?\DateTimeInterface $Publish_date): self
    {
        $this->Publish_date = $Publish_date;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;
        return $this;
    }
}

src/Form/ModelMangaType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\ModelManga;
use Doctrine\DBAL\Types\DateType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType as TypeDateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ModelMangaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name')
            ->add('CharacterName')
            ->add('Series')
            ->add('Price')
            ->add('Material')
            ->add('UsingModel')
            ->add('image',
                    FileType::class,
                    [
                        'label' => 'Image',
                        'data_class' => null,
                        'required' => is_null($builder -> getData() -> getImage()),
                    ])
                    ->add('Category',
                    EntityType::class,
                    [
                        'class' => Category::class,
                        'choice_label' => 'name',
                        'multiple' => false,
                        'expanded' => false
                    ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ModelManga::class,
        ]);
    }
}

src/Controller/ModelMangaController.php
<?php

namespace App\Controller;

use App\Entity\ModelManga;
use App\Form\ModelMangaType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

use function PHPUnit\Framework\throwException;

class ModelMangaController extends AbstractController
{
    /**
     * @Route("/modelmanga", name="modelmanga_index")
     */
    public function index()
    {
        $modelmanga = $this->getDoctrine()->getRepository(ModelManga::class)->findAll();

        return $this->render(
            'model_manga/index.html.twig',
            [
                'modelmanga' => $modelmanga
            ]
        ); 
    }

    /**
     * @Route("/modelmana/detail/{id}", name="modelmanga_detail")
     */
    public function detailModelManga($id) {
        $modelmanga = $this->getDoctrine()->getRepository(ModelManga::class)->find($id);

        return $this->render(
            'model_manga/detail.html.twig',
            [
                'modelmanga' => $modelmanga
            ]
        );
    }

    /**
     * @Route("/modelmanga/create", name="modelmanga_create")
     */
    public function createModelManga(Request $request)
    {
        $modelmanga = new ModelManga();
        $form = $this -> createForm(ModelMangaType::class, $modelmanga);
        $form -> handleRequest($request);

        if($form -> isSubmitted() && $form -> isValid())
        {
            //get image 
            $image = $modelmanga -> getImage();

            //create a unique image name
            $fileName = md5(uniqid());

            //get image extension
            $fileExtension = $image -> guessExtension();
            $imageName = $fileName . '.' . $fileExtension;

            try{
                $image -> move(
                    $this -> getParameter('modelmanga_image'), $imageName
                );
            }
            catch(FileException $e)
            {
                throwException($e);
            }

            $modelmanga -> setImage($imageName);

            $manager = $this -> getDoctrine() -> getManager();
            $manager -> persist($modelmanga);
            $manager -> flush();

            $this -> addFlash("Info","Create successfully!");
            return $this -> redirectToRoute("modelmanga_index");
        }

        
        return $this -> render(
            "model_manga/create.html.twig",
            [
                "form" => $form -> createView()
            ]
        );
    }

    /**
     * @Route("/modelmanga/update{id}", name="modelmanga_update")
     */
    public function updateModelManga(Request $request, $id)
    {
        $modelmanga = $this -> getDoctrine() -> getRepository(ModelManga::class) -> find($id);
        $form = $this -> createForm(ModelMangaType::class, $modelmanga);
        $form -> handleRequest($request);

        if($form -> isSubmitted() && $form -> isValid())
        {
            $uploadFile = $form['image'] -> getData();
            if($uploadFile != null)
            {
                $image = $modelmanga -> getImage();

                //create a unique image name
                $fileName = md5(uniqid());
    
                //get image extension
                $fileExtension = $image -> guessExtension();
                $imageName = $fileName . '.' . $fileExtension;
    
                try{
                    $image -> move(
                        $this -> getParameter('modelmanga_image'), $imageName
                    );
                }
                catch(FileException $e)
                {
                    throwException($e);
                }

                $modelmanga -> setImage($imageName);
            }

            $manager = $this -> getDoctrine() -> getManager();
            $manager -> persist($modelmanga);
            $manager -> flush();

            $this -> addFlash("Info","update successfully!");
            return $this -> redirectToRoute("modelmanga_index");
        }

        $this -> addFlash("Error","update false!");
        return $this -> render(
            "model_manga/update.html.twig",
            [
                "form" => $form -> createView()
            ]
        );
    }

    /**
     * @Route("/modelmanga/delete{id}", name="modelmanga_delete")
     */
    public function deleteModelManga(Request $request, $id)
    {
        $modelmanga = $this -> getDoctrine() -> getRepository(ModelManga::class) -> find($id);

        if($modelmanga != null)
        {
            $manager = $this -> getDoctrine() -> getManager();
            $manager -> remove($modelmanga);
            $manager -> flush();

            $this -> addFlash("Info","delete successfully!");
            return $this -> redirectToRoute("modelmanga_index");
        }

        $this -> addFlash("Error","delete false!");
        return $this -> redirectToRoute("modelmanga_index");
    }
}

templates/model_manga/create.html.twig
{% extends "base.html.twig" %}

{% block body %}
<div class="container">
    <h2 class="mt-5 mb-5 text-center text-success"> Create Model Manga </h2>
    <div class="col-md-6 offset-md-3"></div>
    {{ form_start (form) }}
        <div class="form-group">
            <h6 class="text-primary"> Name </h6>
            {{ form_widget (form.Name, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Character Name </h6>
            {{ form_widget (form.CharacterName, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Series </h6>
            {{ form_widget (form.Series, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Model Price </h6>
            {{ form_widget (form.Price, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Model Material </h6>
            {{ form_widget (form.Material, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Using Model </h6>
            {{ form_widget (form.UsingModel, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Model Image </h6>
            {{ form_widget (form.image, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Category </h6>
            {{ form_widget (form.Category, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group text-center mt-5">
            <button class="btn btn-info mt-2">CREATE</button>
        </div>
    {{ form_end (form) }}
</div>
{% endblock %}

templates/model_manga/detail.html.twig
{% extends "base.html.twig" %}

{% block title %} Model Manga Detail {% endblock %}

{% block body %}
<style>
    body {
        width: 80%;
        margin: 20px auto;
    }
</style>
    <a class="btn btn-outline-success" href="{{ path ('modelmanga_index')}}">Back to list</a>
    <br><br>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Image</th>
                <th scope="col">Character Name</th> 
                <th scope="col">Series</th> 
                <th scope="col">Price</th> 
                <th scope="col">Material</th> 
                <th scope="col">UsingModel</th> 
                
                <th scope="col">Category</th> 
                
            </tr>
        </thead>
        <tbody>
            <tr>
                <td scope="row"> {{ modelmanga.id }} </td>
                <td scope="row"> {{ modelmanga.Name }} </td>
                <td scope="row"> 
                    {% if modelmanga.image == null %}
                         <img src="{{ asset ('images/anh1.jpg')}}" width="300px"> 
                    {% else %}               
                        <img src = "{{asset('images/products/' ~ modelmanga.image)}}" width="300px">
  
                    {% endif %}     
                </td>
                <td scope="row"> {{ modelmanga.CharacterName }} </td>
                <td scope="row"> {{ modelmanga.Series }} </td>
                <td scope="row"> {{ modelmanga.Price }} $</td>
                <td scope="row"> {{ modelmanga.Material }} </td>
                <td scope="row"> {{ modelmanga.UsingModel }} </td>
                <td scope="row">
                         <a href="{{ path ('category_detail', {'id' : modelmanga.category.id} ) }} "> 
                                           {{ modelmanga.category.name }} 
                         </a>
                </td>
                <td>
                    <a class="btn btn-warning" href="{{ path ('modelmanga_update', {'id' : modelmanga.id} )}}">Update</a>
                    <a class="btn btn-danger" href="{{ path ('modelmanga_delete', {'id' : modelmanga.id} )}}"  
                                              onclick = "return confirm ('Are you sure to delete ?')" >      
                    Delete</a>
                </td>
            </tr>
        </tbody>
    </table>
</div>

{% endblock %}

templates/model_manga/index.html.twig
{% extends "base.html.twig" %}

{% block title %} List Moldel Manga {% endblock %}

{% block body %}
<style>
    body {
        width: 80%;
        margin: 20px auto;
    }
</style>
 
<div class="container-fluid">
    <div class="container">
        {% for flash in app.flashes("Info") %}
            <p class="alert alert-success"> {{ flash }}
        {% endfor %}
        {% for flash in app.flashes("Error") %}
            <p class="alert alert-danger"> {{ flash }}
        {% endfor %}
    </div>
    <a class="btn btn-outline-success" href="{{ path ('modelmanga_create') }}">Create Model Manga</a>
    <br><br>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th> 
                <th scope="col">Image</th> 
            </tr>
        </thead>
        <tbody>
        {% for modelmanga in modelmanga %}
            <tr>
                <td scope="row"> {{ modelmanga.id }} </td>
                <td scope="row"> {{ modelmanga.name }} </td>
                <td scope="row"><img src = "{{asset('images/products/' ~ modelmanga.image)}}" width = "300px"></td>
                <td>
                    <a class="btn btn-warning" href="{{ path ('modelmanga_detail', {'id' : modelmanga.id} )}}">Detail</a>   
                    <a class="btn btn-warning" href="{{ path ('modelmanga_update', {'id' : modelmanga.id} )}}">Update</a>
                    <a class="btn btn-danger" href="{{ path ('modelmanga_delete', {'id' : modelmanga.id} )}}"  
                                              onclick = "return confirm ('Are you sure to delete ?')" >      
                    Delete</a>
                </td>
                
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/model_manga/update.html.twig
{% extends "base.html.twig" %}

{% block body %}
<div class="container">
    <h2 class="mt-5 mb-5 text-center text-success"> Update Model Manga </h2>
    <div class="col-md-6 offset-md-3"></div>
    {{ form_start (form) }}
        <div class="form-group">
            <h6 class="text-primary"> Name </h6>
            {{ form_widget (form.Name, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Character Name </h6>
            {{ form_widget (form.CharacterName, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Series </h6>
            {{ form_widget (form.Series, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Model Price </h6>
            {{ form_widget (form.Price, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Model Material </h6>
            {{ form_widget (form.Material, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Using Model </h6>
            {{ form_widget (form.UsingModel, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Model Image </h6>
            {{ form_widget (form.image, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Category </h6>
            {{ form_widget (form.Category, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group text-center mt-5">
            <button class="btn btn-info mt-2">Update Model</button>
        </div>
    {{ form_end (form) }}
</div>
{% endblock %}